language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=grapheme -m py.test
after_success:
  - coveralls
sudo: false
